### ISSUE TITLE
post's featured/first image are not showing on hompage view.

### ISSUE THREAD

**Issue by pambreesh** [hideokamoto/konnichi-an#3]
i dont know if this is by default but on home page posts are showing without featured or any first image. i really need to show images on my hompage with posts. it would be much great if they wud be alligned to left and the rest of the post data to the right. thanks :)

**Comment by hideokamoto** [comment]
Dogfooding now.
https://github.com/hideokamoto/konnichi-an/commit/c6a390b31c6d23402474b8e87957d30c9a1b75ad

**Comment by hideokamoto** [comment]
Now Theme Reviewing.
https://themes.trac.wordpress.org/ticket/29268

**Comment by hideokamoto** [comment]
Updated.
